apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: kiii
data:
  application.properties: |
    spring.datasource.url=jdbc:postgresql://postgres-service:5432/kiii_database
    spring.datasource.username=${DB_USERNAME}
    spring.datasource.password=${DB_PASSWORD}
