version: '3.3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: 'docker-spring-boot-postgres:latest'
    container_name: eshop
    depends_on:
      - db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=data
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/kiii_database
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=data
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - "9090:9090"

  db:
    image: postgres
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=data
      - POSTGRES_DB=kiii_database
    ports:
      - "5432:5432"

