package mk.ukim.finki.wp.eshop.selenium;// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;

public class WpproductsTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void wpproducts() {
    driver.get("http://localhost:9090/");
    driver.manage().window().setSize(new Dimension(1875, 1048));
    driver.findElement(By.linkText("Products")).click();
    driver.findElement(By.id("username")).click();
    driver.findElement(By.id("username")).sendKeys("aleksandar.petrushev");
    driver.findElement(By.id("password")).click();
    driver.findElement(By.id("password")).sendKeys("password");
    driver.findElement(By.id("password")).sendKeys(Keys.ENTER);
    driver.findElement(By.cssSelector(".form-signin")).click();
    driver.findElement(By.id("username")).click();
    driver.findElement(By.id("username")).sendKeys("aleksandar.petrushev");
    driver.findElement(By.id("password")).click();
    driver.findElement(By.id("password")).sendKeys("ap");
    driver.findElement(By.id("password")).sendKeys(Keys.ENTER);
    driver.findElement(By.cssSelector(".product:nth-child(1) .btn")).click();
    driver.findElement(By.linkText("aleksandar.petrushev")).click();
    driver.findElement(By.linkText("Logout")).click();
    driver.findElement(By.id("username")).click();
    driver.findElement(By.id("username")).sendKeys("admin");
    driver.findElement(By.id("password")).sendKeys("admin");
    driver.findElement(By.id("password")).sendKeys(Keys.ENTER);
    driver.findElement(By.cssSelector(".product:nth-child(1) > .text-right .btn")).click();
    driver.findElement(By.linkText("Edit")).click();
    driver.findElement(By.id("submit")).click();
    driver.findElement(By.cssSelector(".product:nth-child(1) .btn-success")).click();
    driver.findElement(By.linkText("Edit current cart")).click();
    driver.findElement(By.id("status")).click();
    driver.findElement(By.cssSelector(".row:nth-child(2)")).click();
    driver.findElement(By.id("status")).click();
    {
      WebElement dropdown = driver.findElement(By.id("status"));
      dropdown.findElement(By.xpath("//option[. = 'FINISHED']")).click();
    }
    driver.findElement(By.cssSelector(".btn-primary")).click();
    driver.findElement(By.cssSelector("html")).click();
  }
}
