name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java JDK 19
        uses: actions/setup-java@v2
        with:
          java-version: '19'

      - name: Compile and test with Maven
        run: mvn clean verify

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/kiii_project:latest .
          docker images  # Optional: Check the built image

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Publish Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/kiii_project:latest

